"""empty message

Revision ID: b19655f04cfd
Revises: 8cd1b6fb87ba
Create Date: 2017-05-07 15:56:24.317363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19655f04cfd'
down_revision = '8cd1b6fb87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('current_news', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('learn_contents', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('party_members', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('work_trends', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_trends', 'content_html')
    op.drop_column('party_members', 'content_html')
    op.drop_column('learn_contents', 'content_html')
    op.drop_column('current_news', 'content_html')
    op.drop_column('activities', 'content_html')
    # ### end Alembic commands ###
